import {
  AppBridge,
  PostMessageTransport,
} from "@modelcontextprotocol/ext-apps/app-bridge";
import { type ReactNode, useEffect, useRef, useState } from "react";
// @ts-expect-error virtual module generated by rollup-plugin-openai-shim
import { OPENAI_SHIM_SCRIPT } from "virtual:openai-shim-script";

import { useProteusDocumentContext } from "../proteus-document/ProteusDocumentContext";
export type ProteusBridgeProps = {
  /**
   * Content rendered on platforms without iframe support
   */
  fallback?: ReactNode;
  /**
   * Height of the iframe in pixels
   */
  height?: number;
  /**
   * Resource URI identifying the MCP app to render
   */
  resource: string;
};

export function ProteusBridge({ height = 400, resource }: ProteusBridgeProps) {
  const { data, onEvent, useResource } = useProteusDocumentContext(
    "@optiaxiom/proteus/ProteusBridge",
  );

  const result = useResource?.(resource);
  const html = result?.data?.text ?? "";
  const mimeType = result?.data?.mimeType;

  const [iframe, setIframe] = useState<HTMLIFrameElement | null>(null);
  const dataRef = useRef(data);
  dataRef.current = data;

  useEffect(() => {
    if (!iframe?.contentWindow) {
      return;
    }

    const bridge = new AppBridge(
      null,
      { name: "Opal", version: "1.0.0" },
      { logging: {}, openLinks: {}, serverTools: {} },
      {
        hostContext: {
          containerDimensions: { maxHeight: iframe.clientHeight },
          displayMode: "inline",
        },
      },
    );

    bridge.oncalltool = async (params) => {
      const result = await onEvent({
        interaction: params.name,
        params: params.arguments ?? {},
      });
      return {
        content: [
          { text: JSON.stringify(result ?? ""), type: "text" as const },
        ],
      };
    };

    bridge.onmessage = async (params) => {
      const message =
        params.content
          ?.filter((content) => content.type === "text")
          .map((content) => content.text)
          .join("\n\n") ?? "";
      await onEvent({ message });
      return {};
    };

    bridge.onopenlink = async ({ url }) => {
      window.open(url, "_blank", "noopener");
      return {};
    };

    bridge.addEventListener("sizechange", ({ height }) => {
      if (height != null) {
        iframe.style.height = `${height}px`;
      }
    });

    bridge.addEventListener("initialized", () => {
      void bridge.sendToolResult({
        content: [
          {
            text: JSON.stringify(dataRef.current),
            type: "text" as const,
          },
        ],
      });
    });

    const transport = new PostMessageTransport(
      iframe.contentWindow,
      iframe.contentWindow,
    );
    void bridge.connect(transport);

    return () => {
      void bridge.close();
    };
  }, [iframe, onEvent]);

  return result?.isError || !html ? null : (
    <iframe
      ref={setIframe}
      sandbox="allow-scripts allow-popups allow-popups-to-escape-sandbox allow-forms"
      srcDoc={
        mimeType === "text/html+skybridge"
          ? (OPENAI_SHIM_SCRIPT as string) + html
          : html
      }
      style={{ border: "none", height, width: "100%" }}
      title="Opal Widget"
    />
  );
}

ProteusBridge.displayName = "@optiaxiom/proteus/ProteusBridge";
