import {
  AppBridge,
  PostMessageTransport,
} from "@modelcontextprotocol/ext-apps/app-bridge";
import { type ReactNode, useEffect, useRef } from "react";
// @ts-expect-error virtual module generated by rollup-plugin-openai-shim
import { OPENAI_SHIM_SCRIPT } from "virtual:openai-shim-script";

import { useProteusDocumentContext } from "../proteus-document/ProteusDocumentContext";
export type ProteusBridgeProps = {
  /**
   * Content rendered on platforms without iframe support
   */
  fallback?: ReactNode;
  /**
   * Height of the iframe in pixels
   */
  height?: number;
  /**
   * Resource URI identifying the MCP app to render
   */
  resource: string;
};

type BridgeCallbacks = {
  data: Record<string, unknown>;
  onInteraction?: (event: {
    data: Record<string, unknown>;
    toolName: string;
    type: string;
  }) => Promise<unknown>;
  onMessage?: (event: { prompt: string; type: string }) => Promise<void>;
};

export function ProteusBridge({ height = 400, resource }: ProteusBridgeProps) {
  const { data, onEvent, useResource } = useProteusDocumentContext(
    "@optiaxiom/proteus/ProteusBridge",
  );

  const result = useResource?.(resource);
  const html = result?.data.html ?? "";
  const mimeType = result?.data.mimeType ?? "text/html";

  const srcDoc =
    mimeType === "text/html;profile=openai-app"
      ? (OPENAI_SHIM_SCRIPT as string) + html
      : html;

  const iframeRef = useRef<HTMLIFrameElement>(null);

  useEffect(() => {
    const iframe = iframeRef.current;
    if (!iframe) return;

    const callbacks: BridgeCallbacks = {
      data,
      onInteraction: async (event) => {
        await onEvent({ interaction: event.toolName });
      },
      onMessage: async (event) => {
        await onEvent({ message: event.prompt });
      },
    };

    return initMcpAppHost(iframe, callbacks);
  }, [data, srcDoc, onEvent, resource]);

  return (
    <iframe
      ref={iframeRef}
      sandbox="allow-scripts allow-popups allow-popups-to-escape-sandbox allow-forms"
      srcDoc={srcDoc}
      style={{ border: "none", height, width: "100%" }}
      title={resource}
    />
  );
}

function initMcpAppHost(
  iframe: HTMLIFrameElement,
  { data, onInteraction, onMessage }: BridgeCallbacks,
): () => void {
  let bridge: AppBridge | undefined;

  const onLoad = () => {
    bridge = new AppBridge(
      null,
      { name: "Opal", version: "1.0.0" },
      { logging: {}, openLinks: {}, serverTools: {} },
      {
        hostContext: {
          containerDimensions: { maxHeight: iframe.clientHeight },
          displayMode: "inline",
        },
      },
    );

    bridge.oncalltool = async (params) => {
      const result = await onInteraction?.({
        data: params.arguments ?? {},
        toolName: params.name,
        type: "callTool",
      });
      return {
        content: [
          { text: JSON.stringify(result ?? ""), type: "text" as const },
        ],
      };
    };

    bridge.onmessage = async (params) => {
      const prompt =
        params.content
          ?.filter(
            (c): c is { text: string; type: "text" } => c.type === "text",
          )
          .map((c) => c.text)
          .join("") ?? "";
      await onMessage?.({ prompt, type: "sendMessage" });
      return {};
    };

    bridge.onopenlink = async ({ url }) => {
      window.open(url, "_blank", "noopener");
      return {};
    };

    bridge.addEventListener("sizechange", ({ height }) => {
      if (height != null) {
        iframe.style.height = `${height}px`;
      }
    });

    bridge.addEventListener("initialized", () => {
      void bridge!.sendToolInput({ arguments: data ?? {} });
      if (data?.toolOutput) {
        void bridge!.sendToolResult({
          content: [
            { text: JSON.stringify(data.toolOutput), type: "text" as const },
          ],
        });
      }
    });

    const transport = new PostMessageTransport(
      iframe.contentWindow!,
      iframe.contentWindow!,
    );
    void bridge.connect(transport);
  };

  iframe.addEventListener("load", onLoad, { once: true });

  return () => {
    iframe.removeEventListener("load", onLoad);
    void bridge?.close();
  };
}

ProteusBridge.displayName = "@optiaxiom/proteus/ProteusBridge";
