import { AxiomProvider } from "@optiaxiom/react";
import { ThemeProvider } from "next-themes";

export const metadata = {
  description: "Generated by Next.js",
  title: "Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <style>
          {`
          html,
          body {
            box-sizing: border-box;
            height: 100%;
            padding: 1rem;
          }
          body {
            align-items: center;
            background: none;
            display: flex;
            flex-direction: column;
            justify-content: center;
            margin: 0;
          }
        `}
        </style>
      </head>
      <body>
        <AxiomProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </AxiomProvider>
      </body>
    </html>
  );
}
