import { createHash } from "node:crypto";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const svgDir = resolve(root, "svg");
const srcDir = resolve(root, "src");

const BASE_URL =
  "https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsrounded";
const AXES = "wght300grad200";
const SIZE = 40;

async function main() {
  const iconsRaw = await readFile(resolve(root, "icons.json"), "utf-8");
  const iconsMap = JSON.parse(iconsRaw);
  const icons = Object.keys(iconsMap);
  const iconsHash = createHash("sha256").update(iconsRaw).digest("hex");

  mkdirSync(svgDir, { recursive: true });

  const tasks = icons.flatMap((icon) => [
    {
      name: `${icon}-fill.svg`,
      url: `${BASE_URL}/${icon}/${AXES}fill1/${SIZE}px.svg`,
    },
    { name: `${icon}.svg`, url: `${BASE_URL}/${icon}/${AXES}/${SIZE}px.svg` },
  ]);

  console.log(`Downloading ${tasks.length} SVGs...`);

  const concurrency = 8;
  let completed = 0;
  let failed = 0;
  let retriesLeft = 3;

  async function downloadTask(task) {
    const filePath = resolve(svgDir, task.name);
    if (existsSync(filePath)) {
      completed++;
      return;
    }
    try {
      const response = await fetch(task.url);
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }
      const svg = await response.text();
      if (!svg.includes("<svg")) {
        throw new Error("Invalid SVG response");
      }
      writeFileSync(filePath, svg);
      completed++;
    } catch (error) {
      if (retriesLeft > 0) {
        retriesLeft--;
        console.error(`\nRetrying: ${task.name} - ${error.message}`);
        await new Promise((r) => setTimeout(r, 1000));
        return downloadTask(task);
      }
      failed++;
      console.error(`\nFailed: ${task.name} - ${error.message}`);
    }
  }

  // Process in batches
  for (let i = 0; i < tasks.length; i += concurrency) {
    const batch = tasks.slice(i, i + concurrency);
    await Promise.all(batch.map(downloadTask));
    process.stdout.write(
      `\r  ${completed + failed}/${tasks.length} (${failed} failed)`,
    );
  }

  console.log(`\nDone. ${completed} downloaded, ${failed} failed.`);

  if (failed > 0) {
    process.exit(1);
  }

  // Collect icons that have _solid aliases (need fill sidecar)
  const needsFillSidecar = new Set();
  for (const [icon, aliases] of Object.entries(iconsMap)) {
    if (aliases?.some((a) => a.endsWith("Solid"))) {
      needsFillSidecar.add(`${icon}-fill.svg`);
    }
  }

  // Generate svg/*.svg.d.ts sidecar files
  const baseIcons = tasks.filter((task) => !task.name.includes("-fill.svg"));
  const fillIcons = tasks.filter((task) => needsFillSidecar.has(task.name));
  for (const task of [...baseIcons, ...fillIcons]) {
    const componentName = svgToComponentName(task.name);
    writeFileSync(
      resolve(svgDir, `${task.name}.d.ts`),
      `import type { IconProps } from "../src/IconProps";\n` +
        `export const ${componentName}: IconProps;\n`,
    );
  }
  console.log(
    `Generated ${baseIcons.length + fillIcons.length} svg/*.svg.d.ts files`,
  );

  // Fetch icon metadata (tags) from Google — skip if tags.json exists and icons.json hasn't changed
  const tagsPath = resolve(root, "tags.json");
  let skipTags = false;
  if (existsSync(tagsPath)) {
    try {
      const existing = JSON.parse(await readFile(tagsPath, "utf-8"));
      if (existing["//hash"] === iconsHash) {
        skipTags = true;
      }
    } catch {
      // tags.json is corrupt or unreadable — regenerate it
    }
  }

  if (skipTags) {
    console.log("tags.json is up to date, skipping metadata fetch.");
  } else {
    console.log("Fetching icon metadata from Google Fonts...");
    const metadataRes = await fetch(
      "https://fonts.google.com/metadata/icons?key=material_symbols&incomplete=true",
    );
    const metadataText = await metadataRes.text();
    // Response starts with )]}\n which needs to be stripped
    const metadata = JSON.parse(metadataText.replace(/^\)]\}'\n/, ""));
    const tagMap = {
      "//": "Auto-generated by scripts/download.mjs - do not edit manually",
      "//hash": iconsHash,
    };
    for (const icon of metadata.icons) {
      if (!icons.includes(icon.name)) continue;
      const aliases = iconsMap[icon.name];
      if (aliases) {
        for (const alias of aliases) {
          tagMap[`Icon${alias}`] = icon.tags;
        }
      }
    }
    writeFileSync(tagsPath, JSON.stringify(tagMap, null, 2) + "\n");
    console.log(
      `Generated tags.json with tags for ${Object.keys(tagMap).length - 2} icons`,
    );
  }

  // Generate src/index.ts (only base icons, filled variants are embedded)
  const indexExports = baseIcons
    .flatMap((task) => {
      const iconName = task.name.replace(/\.svg$/, "");
      const aliases = iconsMap[iconName];
      if (!aliases) {
        return [];
      }
      return aliases.map((alias) => {
        const svgFile = alias.endsWith("Solid")
          ? `${iconName}-fill.svg`
          : task.name;
        return `export { ${svgToComponentName(svgFile)} as Icon${alias} } from "../svg/${svgFile}";`;
      });
    })
    .sort((a, b) => {
      const pathA = a.match(/from "(.+)"/)?.[1] ?? "";
      const pathB = b.match(/from "(.+)"/)?.[1] ?? "";
      return pathA < pathB
        ? -1
        : pathA > pathB
          ? 1
          : a < b
            ? -1
            : a > b
              ? 1
              : 0;
    })
    .join("\n");

  writeFileSync(
    resolve(srcDir, "index.ts"),
    `// Auto-generated by scripts/download.mjs - do not edit manually\n\n${indexExports}\n`,
  );
  console.log("Generated src/index.ts");
}

function svgToComponentName(svgFileName) {
  const name = svgFileName.replace(/\.svg$/, "").replace(/-fill$/, "_fill");

  const pascal = name
    .split("_")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");

  return `Icon${pascal}`;
}

main();
