import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const svgDir = resolve(root, "svg");
const srcDir = resolve(root, "src");

const BASE_URL =
  "https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsrounded";
const AXES = "wght300grad200";
const SIZE = 40;

async function main() {
  const icons = JSON.parse(
    await readFile(resolve(root, "icons.json"), "utf-8"),
  );

  mkdirSync(svgDir, { recursive: true });

  const tasks = icons.flatMap((icon) => [
    {
      name: `${icon}-fill.svg`,
      url: `${BASE_URL}/${icon}/${AXES}fill1/${SIZE}px.svg`,
    },
    { name: `${icon}.svg`, url: `${BASE_URL}/${icon}/${AXES}/${SIZE}px.svg` },
  ]);

  console.log(`Downloading ${tasks.length} SVGs...`);

  const concurrency = 8;
  let completed = 0;
  let failed = 0;

  async function downloadTask(task) {
    const filePath = resolve(svgDir, task.name);
    if (existsSync(filePath)) {
      completed++;
      return;
    }
    try {
      const response = await fetch(task.url);
      if (!response.ok) {
        throw new Error(`HTTP ${response.status}`);
      }
      const svg = await response.text();
      if (!svg.includes("<svg")) {
        throw new Error("Invalid SVG response");
      }
      writeFileSync(filePath, svg);
      completed++;
    } catch (error) {
      failed++;
      console.error(`Failed: ${task.name} - ${error.message}`);
    }
  }

  // Process in batches
  for (let i = 0; i < tasks.length; i += concurrency) {
    const batch = tasks.slice(i, i + concurrency);
    await Promise.all(batch.map(downloadTask));
    process.stdout.write(
      `\r  ${completed + failed}/${tasks.length} (${failed} failed)`,
    );
  }

  console.log(`\nDone. ${completed} downloaded, ${failed} failed.`);

  if (failed > 0) {
    process.exit(1);
  }

  // Generate svg/*.svg.d.ts sidecar files (only for base icons, not -fill variants)
  const baseIcons = tasks.filter((task) => !task.name.includes("-fill.svg"));
  for (const task of baseIcons) {
    const componentName = svgToComponentName(task.name);
    writeFileSync(
      resolve(svgDir, `${task.name}.d.ts`),
      `import type { IconProps } from "../src/IconProps";\n` +
        `export const ${componentName}: IconProps;\n`,
    );
  }
  console.log(`Generated ${baseIcons.length} svg/*.svg.d.ts files`);

  // Fetch icon metadata (tags) from Google
  console.log("Fetching icon metadata from Google Fonts...");
  const metadataRes = await fetch(
    "https://fonts.google.com/metadata/icons?key=material_symbols&incomplete=true",
  );
  const metadataText = await metadataRes.text();
  // Response starts with )]}\n which needs to be stripped
  const metadata = JSON.parse(metadataText.replace(/^\)]\}'\n/, ""));
  const tagMap = {
    "//": "Auto-generated by scripts/download.mjs - do not edit manually",
  };
  for (const icon of metadata.icons) {
    if (icons.includes(icon.name)) {
      tagMap[svgToComponentName(icon.name)] = icon.tags;
    }
  }
  writeFileSync(
    resolve(root, "tags.json"),
    JSON.stringify(tagMap, null, 2) + "\n",
  );
  console.log(
    `Generated tags.json with tags for ${Object.keys(tagMap).length - 1} icons`,
  );

  // Generate src/index.ts (only base icons, filled variants are embedded)
  const indexExports = baseIcons
    .map((task) => {
      const componentName = svgToComponentName(task.name);
      return `export { ${componentName} } from "../svg/${task.name}";`;
    })
    .join("\n");

  writeFileSync(resolve(srcDir, "index.ts"), `${indexExports}\n`);
  console.log("Generated src/index.ts");
}

function svgToComponentName(svgFileName) {
  const name = svgFileName.replace(/\.svg$/, "").replace(/-fill$/, "");

  const pascal = name
    .split("_")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");

  return `Icon${pascal}`;
}

main();
