export const demos = {
  "alert-dialog/async-usage": import("./alert-dialog/async-usage/App"),
  "alert-dialog/confirmation-usage": import(
    "./alert-dialog/confirmation-usage/App"
  ),
  "alert-dialog/controlled-usage": import(
    "./alert-dialog/controlled-usage/App"
  ),
  "alert-dialog/size-usage": import("./alert-dialog/size-usage/App"),
  "alert-dialog/trigger-usage": import("./alert-dialog/trigger-usage/App"),
  "alert-dialog/usage": import("./alert-dialog/usage/App"),
  "alert/appearance-usage": import("./alert/appearance-usage/App"),
  "alert/close-usage": import("./alert/close-usage/App"),
  "alert/usage": import("./alert/usage/App"),
  "animation/pulse-usage": import("./animation/pulse-usage/App"),
  "autocomplete/complex-usage": import("./autocomplete/complex-usage/App"),
  "autocomplete/controlled-usage": import(
    "./autocomplete/controlled-usage/App"
  ),
  "autocomplete/creatable-usage": import("./autocomplete/creatable-usage/App"),
  "autocomplete/loading-usage": import("./autocomplete/loading-usage/App"),
  "autocomplete/usage": import("./autocomplete/usage/App"),
  "autocomplete/virtualized-usage": import(
    "./autocomplete/virtualized-usage/App"
  ),
  "avatar/color-usage": import("./avatar/color-usage/App"),
  "avatar/fallback-children-usage": import(
    "./avatar/fallback-children-usage/App"
  ),
  "avatar/fallback-icon-usage": import("./avatar/fallback-icon-usage/App"),
  "avatar/fallback-name-usage": import("./avatar/fallback-name-usage/App"),
  "avatar/group-usage": import("./avatar/group-usage/App"),
  "avatar/size-usage": import("./avatar/size-usage/App"),
  "avatar/usage": import("./avatar/usage/App"),
  "background-color/usage": import("./background-color/usage/App"),
  "badge/appearance-usage": import("./badge/appearance-usage/App"),
  "badge/link-usage": import("./badge/link-usage/App"),
  "badge/usage": import("./badge/usage/App"),
  "banner/appearance-usage": import("./banner/appearance-usage/App"),
  "banner/close-usage": import("./banner/close-usage/App"),
  "banner/usage": import("./banner/usage/App"),
  "border-color/usage": import("./border-color/usage/App"),
  "border-radius/usage": import("./border-radius/usage/App"),
  "border-width/single-usage": import("./border-width/single-usage/App"),
  "border-width/usage": import("./border-width/usage/App"),
  "box-shadow/none-usage": import("./box-shadow/none-usage/App"),
  "box-shadow/usage": import("./box-shadow/usage/App"),
  "box/composition-usage": import("./box/composition-usage/App"),
  "box/usage": import("./box/usage/App"),
  "button/appearance-usage": import("./button/appearance-usage/App"),
  "button/disabled-usage": import("./button/disabled-usage/App"),
  "button/file-upload-usage": import("./button/file-upload-usage/App"),
  "button/group-usage": import("./button/group-usage/App"),
  "button/icon-only-usage": import("./button/icon-only-usage/App"),
  "button/icon-usage": import("./button/icon-usage/App"),
  "button/link-disabled-usage": import("./button/link-disabled-usage/App"),
  "button/link-usage": import("./button/link-usage/App"),
  "button/loading-usage": import("./button/loading-usage/App"),
  "button/size-usage": import("./button/size-usage/App"),
  "button/usage": import("./button/usage/App"),
  "calendar/usage": import("./calendar/usage/App"),
  "card/usage": import("./card/usage/App"),
  "checkbox/controlled-usage": import("./checkbox/controlled-usage/App"),
  "checkbox/description-usage": import("./checkbox/description-usage/App"),
  "checkbox/disabled-usage": import("./checkbox/disabled-usage/App"),
  "checkbox/indeterminate-usage": import("./checkbox/indeterminate-usage/App"),
  "checkbox/label-usage": import("./checkbox/label-usage/App"),
  "checkbox/usage": import("./checkbox/usage/App"),
  "code/usage": import("./code/usage/App"),
  "color/usage": import("./color/usage/App"),
  "combobox/usage": import("./combobox/usage/App"),
  "data-table/usage": import("./data-table/usage/App"),
  "date-input/usage": import("./date-input/usage/App"),
  "dialog/alert-dialog-usage": import("./dialog/alert-dialog-usage/App"),
  "dialog/controlled-usage": import("./dialog/controlled-usage/App"),
  "dialog/description-usage": import("./dialog/description-usage/App"),
  "dialog/form-usage": import("./dialog/form-usage/App"),
  "dialog/nested-usage": import("./dialog/nested-usage/App"),
  "dialog/size-usage": import("./dialog/size-usage/App"),
  "dialog/trigger-usage": import("./dialog/trigger-usage/App"),
  "dialog/usage": import("./dialog/usage/App"),
  "disclosure/addon-usage": import("./disclosure/addon-usage/App"),
  "disclosure/chevron-position-usage": import(
    "./disclosure/chevron-position-usage/App"
  ),
  "disclosure/usage": import("./disclosure/usage/App"),
  "dropdown-menu/addon-usage": import("./dropdown-menu/addon-usage/App"),
  "dropdown-menu/alert-dialog-usage": import(
    "./dropdown-menu/alert-dialog-usage/App"
  ),
  "dropdown-menu/appearance-usage": import(
    "./dropdown-menu/appearance-usage/App"
  ),
  "dropdown-menu/checkbox-usage": import("./dropdown-menu/checkbox-usage/App"),
  "dropdown-menu/controlled-usage": import(
    "./dropdown-menu/controlled-usage/App"
  ),
  "dropdown-menu/description-usage": import(
    "./dropdown-menu/description-usage/App"
  ),
  "dropdown-menu/disabled-usage": import("./dropdown-menu/disabled-usage/App"),
  "dropdown-menu/ellipsis-trigger-usage": import(
    "./dropdown-menu/ellipsis-trigger-usage/App"
  ),
  "dropdown-menu/modal-usage": import("./dropdown-menu/modal-usage/App"),
  "dropdown-menu/nested-usage": import("./dropdown-menu/nested-usage/App"),
  "dropdown-menu/position-usage": import("./dropdown-menu/position-usage/App"),
  "dropdown-menu/select-usage": import("./dropdown-menu/select-usage/App"),
  "dropdown-menu/trigger-usage": import("./dropdown-menu/trigger-usage/App"),
  "dropdown-menu/usage": import("./dropdown-menu/usage/App"),
  "field/description-usage": import("./field/description-usage/App"),
  "field/error-usage": import("./field/error-usage/App"),
  "field/info-usage": import("./field/info-usage/App"),
  "field/required-usage": import("./field/required-usage/App"),
  "field/usage": import("./field/usage/App"),
  "flex/alignment-usage": import("./flex/alignment-usage/App"),
  "flex/gap-usage": import("./flex/gap-usage/App"),
  "flex/horizontal-usage": import("./flex/horizontal-usage/App"),
  "flex/usage": import("./flex/usage/App"),
  "flex/vertical-usage": import("./flex/vertical-usage/App"),
  "font/family-usage": import("./font/family-usage/App"),
  "font/size-usage": import("./font/size-usage/App"),
  "gap/usage": import("./gap/usage/App"),
  "grid/gap-usage": import("./grid/gap-usage/App"),
  "grid/span-usage": import("./grid/span-usage/App"),
  "grid/usage": import("./grid/usage/App"),
  "heading/size-usage": import("./heading/size-usage/App"),
  "heading/usage": import("./heading/usage/App"),
  "height/usage": import("./height/usage/App"),
  "indicator/appearance-usage": import("./indicator/appearance-usage/App"),
  "indicator/content-usage": import("./indicator/content-usage/App"),
  "indicator/disabled-usage": import("./indicator/disabled-usage/App"),
  "indicator/usage": import("./indicator/usage/App"),
  "inline-input/appearance-usage": import(
    "./inline-input/appearance-usage/App"
  ),
  "inline-input/change-usage": import("./inline-input/change-usage/App"),
  "inline-input/controlled-usage": import(
    "./inline-input/controlled-usage/App"
  ),
  "inline-input/disabled-usage": import("./inline-input/disabled-usage/App"),
  "inline-input/multiline-usage": import("./inline-input/multiline-usage/App"),
  "inline-input/placeholder-usage": import(
    "./inline-input/placeholder-usage/App"
  ),
  "inline-input/usage": import("./inline-input/usage/App"),
  "input/addon-pointer-usage": import("./input/addon-pointer-usage/App"),
  "input/addon-usage": import("./input/addon-usage/App"),
  "input/disabled-usage": import("./input/disabled-usage/App"),
  "input/error-usage": import("./input/error-usage/App"),
  "input/readonly-usage": import("./input/readonly-usage/App"),
  "input/size-usage": import("./input/size-usage/App"),
  "input/usage": import("./input/usage/App"),
  "kbd/appearance-usage": import("./kbd/appearance-usage/App"),
  "kbd/keys-usage": import("./kbd/keys-usage/App"),
  "kbd/usage": import("./kbd/usage/App"),
  "link/appearance-usage": import("./link/appearance-usage/App"),
  "link/button-usage": import("./link/button-usage/App"),
  "link/disabled-usage": import("./link/disabled-usage/App"),
  "link/external-usage": import("./link/external-usage/App"),
  "link/usage": import("./link/usage/App"),
  "margin/multiple-usage": import("./margin/multiple-usage/App"),
  "margin/single-usage": import("./margin/single-usage/App"),
  "margin/usage": import("./margin/usage/App"),
  "max-height/usage": import("./max-height/usage/App"),
  "max-width/usage": import("./max-width/usage/App"),
  "modal-layer/usage": import("./modal-layer/usage/App"),
  "padding/multiple-usage": import("./padding/multiple-usage/App"),
  "padding/single-usage": import("./padding/single-usage/App"),
  "padding/usage": import("./padding/usage/App"),
  "pagination/controlled-usage": import("./pagination/controlled-usage/App"),
  "pagination/usage": import("./pagination/usage/App"),
  "pill/disabled-usage": import("./pill/disabled-usage/App"),
  "pill/group-usage": import("./pill/group-usage/App"),
  "pill/size-usage": import("./pill/size-usage/App"),
  "pill/usage": import("./pill/usage/App"),
  "popover/controlled-usage": import("./popover/controlled-usage/App"),
  "popover/example-usage": import("./popover/example-usage/App"),
  "popover/trigger-usage": import("./popover/trigger-usage/App"),
  "popover/usage": import("./popover/usage/App"),
  "progress/appearance-usage": import("./progress/appearance-usage/App"),
  "progress/usage": import("./progress/usage/App"),
  "radio-group/controlled-usage": import("./radio-group/controlled-usage/App"),
  "radio-group/description-usage": import(
    "./radio-group/description-usage/App"
  ),
  "radio-group/disabled-group-usage": import(
    "./radio-group/disabled-group-usage/App"
  ),
  "radio-group/disabled-usage": import("./radio-group/disabled-usage/App"),
  "radio-group/label-usage": import("./radio-group/label-usage/App"),
  "radio-group/usage": import("./radio-group/usage/App"),
  "search-input/controlled-usage": import(
    "./search-input/controlled-usage/App"
  ),
  "search-input/disabled-usage": import("./search-input/disabled-usage/App"),
  "search-input/usage": import("./search-input/usage/App"),
  "segmented-control/controlled-usage": import(
    "./segmented-control/controlled-usage/App"
  ),
  "segmented-control/usage": import("./segmented-control/usage/App"),
  "select/usage": import("./select/usage/App"),
  "separator/responsive-usage": import("./separator/responsive-usage/App"),
  "separator/usage": import("./separator/usage/App"),
  "separator/vertical-usage": import("./separator/vertical-usage/App"),
  "sidebar/account-item/usage": import("./sidebar/account-item/usage/App"),
  "sidebar/group/separator-usage": import(
    "./sidebar/group/separator-usage/App"
  ),
  "sidebar/group/usage": import("./sidebar/group/usage/App"),
  "sidebar/item/active-usage": import("./sidebar/item/active-usage/App"),
  "sidebar/item/link-usage": import("./sidebar/item/link-usage/App"),
  "sidebar/item/usage": import("./sidebar/item/usage/App"),
  "sidebar/panel/sub-usage": import("./sidebar/panel/sub-usage/App"),
  "sidebar/panel/usage": import("./sidebar/panel/usage/App"),
  "sidebar/section/sub-usage": import("./sidebar/section/sub-usage/App"),
  "sidebar/section/usage": import("./sidebar/section/usage/App"),
  "sidebar/sub-nav-usage": import("./sidebar/sub-nav-usage/App"),
  "sidebar/toggle/usage": import("./sidebar/toggle/usage/App"),
  "sidebar/usage": import("./sidebar/usage/App"),
  "size/percentage-usage": import("./size/percentage-usage/App"),
  "size/reset-usage": import("./size/reset-usage/App"),
  "size/usage": import("./size/usage/App"),
  "skeleton/children-usage": import("./skeleton/children-usage/App"),
  "skeleton/dimension-usage": import("./skeleton/dimension-usage/App"),
  "skeleton/example-usage": import("./skeleton/example-usage/App"),
  "skeleton/usage": import("./skeleton/usage/App"),
  "spinner/color-usage": import("./spinner/color-usage/App"),
  "spinner/label-usage": import("./spinner/label-usage/App"),
  "spinner/size-usage": import("./spinner/size-usage/App"),
  "spinner/usage": import("./spinner/usage/App"),
  "styles/css-usage": import("./styles/css-usage/App"),
  "styles/js-usage": import("./styles/js-usage/App"),
  "styles/prop-usage": import("./styles/prop-usage/App"),
  "styles/responsive-complex-usage": import(
    "./styles/responsive-complex-usage/App"
  ),
  "styles/responsive-usage": import("./styles/responsive-usage/App"),
  "switch/controlled-usage": import("./switch/controlled-usage/App"),
  "switch/disabled-usage": import("./switch/disabled-usage/App"),
  "switch/label-usage": import("./switch/label-usage/App"),
  "switch/size-usage": import("./switch/size-usage/App"),
  "switch/usage": import("./switch/usage/App"),
  "table/usage": import("./table/usage/App"),
  "tabs/usage": import("./tabs/usage/App"),
  "text/composition-usage": import("./text/composition-usage/App"),
  "text/formatting-usage": import("./text/formatting-usage/App"),
  "text/line-clamp-usage": import("./text/line-clamp-usage/App"),
  "text/truncate-usage": import("./text/truncate-usage/App"),
  "text/usage": import("./text/usage/App"),
  "textarea/addon-pointer-usage": import("./textarea/addon-pointer-usage/App"),
  "textarea/addon-usage": import("./textarea/addon-usage/App"),
  "textarea/disabled-usage": import("./textarea/disabled-usage/App"),
  "textarea/error-usage": import("./textarea/error-usage/App"),
  "textarea/readonly-usage": import("./textarea/readonly-usage/App"),
  "textarea/size-auto-minmax-usage": import(
    "./textarea/size-auto-minmax-usage/App"
  ),
  "textarea/size-auto-usage": import("./textarea/size-auto-usage/App"),
  "textarea/size-manual-usage": import("./textarea/size-manual-usage/App"),
  "textarea/size-reset-usage": import("./textarea/size-reset-usage/App"),
  "textarea/size-usage": import("./textarea/size-usage/App"),
  "textarea/usage": import("./textarea/usage/App"),
  "toast/action-usage": import("./toast/action-usage/App"),
  "toast/appearance-usage": import("./toast/appearance-usage/App"),
  "toast/dismiss-usage": import("./toast/dismiss-usage/App"),
  "toast/usage": import("./toast/usage/App"),
  "toggle-button/appearance-usage": import(
    "./toggle-button/appearance-usage/App"
  ),
  "toggle-button/controlled-usage": import(
    "./toggle-button/controlled-usage/App"
  ),
  "toggle-button/disabled-usage": import("./toggle-button/disabled-usage/App"),
  "toggle-button/usage": import("./toggle-button/usage/App"),
  "tooltip/controlled-usage": import("./tooltip/controlled-usage/App"),
  "tooltip/delay-usage": import("./tooltip/delay-usage/App"),
  "tooltip/placement-usage": import("./tooltip/placement-usage/App"),
  "tooltip/usage": import("./tooltip/usage/App"),
  "transition/colors-usage": import("./transition/colors-usage/App"),
  "width/percentage-usage": import("./width/percentage-usage/App"),
  "width/usage": import("./width/usage/App"),
  "z-index/usage": import("./z-index/usage/App"),
};
